//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("webpages_CauHinh")]
    public partial class CauHinhModel
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        
        public string Ten { get; set; }

        [ForeignKey("PLAN_HocKyDangKy_TC")]
        public int? Ky_dang_ky { get; set; }

        public string Gia_tri { get; set; }

        public string Kieu { get; set; }

        public string Mo_ta { get; set; }

        public virtual PLAN_HocKyDangKy_TC PLAN_HocKyDangKy_TC { get; set; }
    }
}
