//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    [Table("ACC_HoatDongKhoaHocCongNghe")]
    public partial class ACC_HoatDongKhoaHocCongNghe
    {
        public int ID_khcn { get; set; }
        public int ID_sv { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public string Ten_de_tai { get; set; }
        public System.DateTime Ngay_thang { get; set; }
        public string Nguoi_huong_dan { get; set; }
        public string Noi_dung_bao_cao { get; set; }
        public string Cap_bao_cao { get; set; }
        public string Giai_thuong { get; set; }
        public Nullable<int> Diem_thuong { get; set; }
    }
}
