//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("MARK_Diem")]
    public partial class MARK_Diem
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_diem { get; set; }
		
		[Display(Name = "ID_dv")]
        public string ID_dv { get; set; }
		
		[Display(Name = "ID_sv")]
		[ForeignKey("STU_HoSoSinhVien")]
        public int ID_sv { get; set; }
		
		[Display(Name = "ID Môn")]
		[ForeignKey("MARK_MonHoc")]
        public int ID_mon { get; set; }
		
		[Display(Name = "ID_dt")]
		//[ForeignKey("PLAN_ChuongTrinhDaoTao")]
        public int ID_dt { get; set; }
		
		[Display(Name = "TBCHP lần 1")]
        public Nullable<float> TBCHP_Lan1 { get; set; }
		
		[Display(Name = "TBCHP Max")]
        public Nullable<float> TBCHP_Max { get; set; }
		
		[Display(Name = "TBCHPs")]
        public string TBCHPs { get; set; }
		
		[Display(Name = "Học kỳ")]
        public int Hoc_ky { get; set; }
		
		[Display(Name = "Năm học")]
        public string Nam_hoc { get; set; }

        public virtual STU_HoSoSinhVien STU_HoSoSinhVien { get; set; }
		
		public virtual MARK_MonHoc MARK_MonHoc { get; set; }
		
		//public virtual PLAN_ChuongTrinhDaoTao PLAN_ChuongTrinhDaoTap{ get; set; }
    }
}
