//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_ToaNhaKyTucXa")]
    public partial class STU_ToaNhaKyTucXa
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_nha_ktx { get; set; }
		
		[Display(Name = "Mã nhà")]
        public string Ma_nha { get; set; }
		
		[Display(Name = "Tên nhà")]
        public string Ten_nha { get; set; }
    }
}
