//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    [Table("ACC_LoaiQuy")]
    public partial class ACC_LoaiQuy
    {
        public int ID_quy { get; set; }
        public string Loai_quy { get; set; }
        public string Ghi_chu { get; set; }
    }
}
