//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("Mark_XetLenLop")]
    public partial class Mark_XetLenLop
    {
		[Display(Name = "Học kỳ")]
        [Key, Column(Order = 2)]
        public int Hoc_ky { get; set; }
		
		[Display(Name = "Năm học")]
        [Key, Column(Order = 1)]
        public string Nam_hoc { get; set; }
		
		[Display(Name = "ID_sv")]
		[ForeignKey("STU_HoSoSinhVien")]
        [Key, Column(Order=0)]
        public int ID_sv { get; set; }
		
		[Display(Name = "Lần cảnh báo")]
        public int Lan_canh_bao { get; set; }
		
		[Display(Name = "Lý do")]
        public string Ly_do { get; set; }
		
		[Display(Name = "Số TCTL")]
        public Nullable<double> So_TCTL { get; set; }
		
		[Display(Name = "TBCTL")]
        public Nullable<double> TBCTL { get; set; }
		
		[Display(Name = "Số TCHT")]
        public Nullable<double> So_TCHT { get; set; }
		
		[Display(Name = "TBCHT Kỳ")]
        public Nullable<double> TBCHT_Ky { get; set; }
		
		[Display(Name = "Duyệt")]
        public Nullable<bool> Duyet { get; set; }
		
		public virtual STU_HoSoSinhVien STU_HoSoSinhVien { get; set; }
    }
}
