//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("MARK_Diem_TC")]
    public partial class MARK_Diem_TC
    {
		//public MARK_Diem_TC()
		//{
		//	this.MARK_DiemThanhPhan_TC = new HashSet<MARK_DiemThanhPhan_TC>();
		//	this.MARK_DiemThi_TC = new HashSet<MARK_DiemThi_TC>();
		//}
		
		[Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_diem { get; set; }
		
		[Display(Name = "ID_dv")]
        public string ID_dv { get; set; }
		
		[Display(Name = "ID_sv")]
		[ForeignKey("STU_HoSoSinhVien")]
        public int ID_sv { get; set; }
		
		[Display(Name = "ID Môn")]
		[ForeignKey("MARK_MonHoc")]
        public int ID_mon { get; set; }
		
		[Display(Name = "ID_dt")]
		//[ForeignKey("PLAN_ChuongTrinhDaoTao")]
        public int ID_dt { get; set; }
		
		[Display(Name = "TBCMH lần 1")]
        public Nullable<float> TBCMH_Lan1 { get; set; }
		
		[Display(Name = "TBCMH Max")]
        public Nullable<float> TBCMH_Max { get; set; }
		
		[Display(Name = "Điểm thi")]
        public string DIEM_THIs { get; set; }
		
		[Display(Name = "Điểm chữ")]
        public string DIEM_CHUs { get; set; }
		
		[Display(Name = "Học kỳ")]
        public int Hoc_ky { get; set; }
		
		[Display(Name = "Năm học")]
        public string Nam_hoc { get; set; }
		
		[Display(Name = "Duyệt")]
        public Nullable<bool> Duyet { get; set; }
		
		[Display(Name = "Tính tích lũy")]
        public Nullable<bool> Tinh_tich_luy { get; set; }

		public virtual MARK_MonHoc MARK_MonHoc { get; set; }

		//public virtual PLAN_ChuongTrinhDaoTao PLAN_ChuongTrinhDaoTao { get; set; }

		public virtual STU_HoSoSinhVien STU_HoSoSinhVien { get; set; }
		
		//public virtual ICollection<MARK_DiemThanhPhan_TC> MARK_DiemThanhPhan_TC { get; set; }
		//public virtual ICollection<MARK_DiemThi_TC> MARK_DiemThi_TC { get; set; }
    }
}
