//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_ChucDanh")]
    public partial class STU_ChucDanh
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_chuc_danh { get; set; }
		
		[Display(Name = "Chức danh")]
        public string Chuc_danh { get; set; }
		
		[Display(Name = "Điểm thưởng")]
        public Nullable<float> Diem_thuong { get; set; }
    }
}
