//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_RangBuocNganhNhapHoc")]
    public partial class STU_RangBuocNganhNhapHoc
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_rb { get; set; }
		
		[Display(Name = "Năm học")]
        public int Nam_hoc { get; set; }
		
		[Display(Name = "Loại")]
        public int Loai { get; set; }
		
		[Display(Name = "ID ngành")]
		[ForeignKey("STU_Nganh")]
        public Nullable<int> ID_Nganh { get; set; }
		
		[Display(Name = "ID Chuyên ngành")]
		[ForeignKey("STU_ChuyenNganh")]
        public int ID_chuyen_nganh { get; set; }

        public virtual STU_Nganh STU_Nganh { get; set; }

        public virtual STU_ChuyenNganh STU_ChuyenNganh { get; set; }
    }
}
