//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_PhongKyTucXa")]
    public partial class STU_PhongKyTucXa
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_phong_KTX { get; set; }
		
		[Display(Name = "ID Nhà KTX")]
		[ForeignKey("STU_ToaNhaKyTucXa")]
        public Nullable<int> ID_nha_KTX { get; set; }
		
		[Display(Name = "ID Tầng")]
		[ForeignKey("PLAN_TANG")]
        public Nullable<int> ID_tang { get; set; }
		
		[Display(Name = "Số phòng KTX")]
        public string So_phong_KTX { get; set; }
		
		[Display(Name = "Sức chứa")]
        public Nullable<int> Suc_chua { get; set; }
		
		[Display(Name = "Thiết bị")]
        public string Thiet_bi { get; set; }
		
		[Display(Name = "Số tiền / người")]
        public Nullable<int> So_tien_mot_nguoi { get; set; }
		
		[Display(Name = "ID Cơ sở")]
		[ForeignKey("PLAN_COSODAOTAO")]
        public Nullable<int> ID_co_so { get; set; }
		
		public virtual STU_ToaNhaKyTucXa STU_ToaNhaKyTucXa { get; set; }
		
		public virtual PLAN_TANG PLAN_TANG { get; set; }
		
		public virtual PLAN_COSODAOTAO PLAN_COSODAOTAO { get; set; }
    }
}
