//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_LoaiCongViec
    {
        public int ID_loai_cv { get; set; }
        public string Ma_loai_cv { get; set; }
        public int ID_nhom_cv { get; set; }
        public string Loai_cong_viec { get; set; }
        public int Tu_sv { get; set; }
        public int Den_sv { get; set; }
        public float So_luong { get; set; }
        public string Don_vi { get; set; }
        public float Gio_chuan { get; set; }
    }
}
