//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_LoaiThuChi
    {
        public int ID_thu_chi { get; set; }
        public string Ten_thu_chi { get; set; }
        public bool Thu_chi { get; set; }
        public long So_tien { get; set; }
        public bool Thu_bat_buoc { get; set; }
        public bool Theo_nien_khoa { get; set; }
        public Nullable<bool> Hoc_phi { get; set; }
        public Nullable<int> ID_he { get; set; }
        public Nullable<int> Khoa_hoc { get; set; }
    }
}
