//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_MucHocPhiTinChi
    {
        public int ID { get; set; }
        public Nullable<int> Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public Nullable<int> ID_he { get; set; }
        public Nullable<int> Ngoai_ngan_sach { get; set; }
        public Nullable<bool> Lop_chat_luong_cao { get; set; }
        public Nullable<int> Nganh2 { get; set; }
        public Nullable<int> Hoc_lai { get; set; }
        public Nullable<int> Mien_giam { get; set; }
        public string Tinh_chat { get; set; }
        public Nullable<int> So_tien { get; set; }
        public Nullable<int> Khoa_hoc { get; set; }
        public int Muc_thuc_hanh { get; set; }
        public int ID_chuyen_nganh { get; set; }
        public int Kinh_te { get; set; }
    }
}
