//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_Diem
    {
        [Key]
        public int ID_diem { get; set; }
        public string ID_dv { get; set; }
        public int ID_sv { get; set; }
        public int ID_mon { get; set; }
        public int ID_dt { get; set; }
        public Nullable<float> TBCHP_Lan1 { get; set; }
        public Nullable<float> TBCHP_Max { get; set; }
        public string TBCHPs { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
    }
}
