//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark_DanhSachNgunghoc
    {
        [Key]
        public int ID_ngung_hoc { get; set; }
        public int ID_sv { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public string So_QD { get; set; }
        public Nullable<System.DateTime> Ngay_QD { get; set; }
        public string Ly_do { get; set; }
        public int ID_lop_cu { get; set; }
        public bool Thoi_hoc { get; set; }
        public bool Nghi_hoc { get; set; }
        public bool Chuyen_truong { get; set; }
    }
}
