//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_ThiTotNghiep_DangKy
    {
        [Key]
        public int ID_SV { get; set; }
        public bool SinhVien_Duyet { get; set; }
        public bool CoVan_Duyet { get; set; }
    }
}
