//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_QuyetDinhThoiHoc
    {
        [Key]
        public int ID_qd { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public string So_qd { get; set; }
        public System.DateTime Ngay_qd { get; set; }
        public int Loai_qd { get; set; }
        public string Ly_do { get; set; }
    }
}
