//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_ToChucThiPhucKhao_TC
    {
        [Key]
        public int ID_phuc_khao { get; set; }
        public int ID_thi { get; set; }
        public int ID_ds_thi { get; set; }
        public int Lan { get; set; }
        public Nullable<float> Diem1 { get; set; }
        public Nullable<float> Diem2 { get; set; }
        public string Ghi_chu { get; set; }
    }
}
