//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark_XetLenLop
    {
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int ID_sv { get; set; }
        public int Lan_canh_bao { get; set; }
        public string Ly_do { get; set; }
        public Nullable<double> So_TCTL { get; set; }
        public Nullable<double> TBCTL { get; set; }
        public Nullable<double> So_TCHT { get; set; }
        public Nullable<double> TBCHT_Ky { get; set; }
        public Nullable<bool> Duyet { get; set; }
    }
}
