//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("MARK_DiemRenLuyen")]
    public partial class MARK_DiemRenLuyen
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_diem_rl { get; set; }
		
		[Display(Name = "Học kỳ")]
        public int Hoc_ky { get; set; }
		
		[Display(Name = "Năm học")]
        public string Nam_hoc { get; set; }
		
		[Display(Name = "ID_sv")]
		[ForeignKey("STU_HoSoSinhVien")]
        public int ID_sv { get; set; }
		
		[Display(Name = "ID Loại RL")]
		[ForeignKey("STU_LoaiRenLuyen")]
        public int ID_loai_rl { get; set; }
		
		[Display(Name = "Điểm")]
        public int Diem { get; set; }
		
		[Display(Name = "Locked")]
        public bool Locked { get; set; }
		
		public virtual STU_HoSoSinhVien STU_HoSoSinhVien { get; set; }
		
		public virtual STU_LoaiRenLuyen STU_LoaiRenLuyen { get; set; }
    }
}
