//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_DiemDanh
    {
        [Key]
        public int ID_diem_danh { get; set; }
        public int ID_diem { get; set; }
        public int Lan_hoc { get; set; }
        public int So_tiet_nghi { get; set; }
        public int Hash_code { get; set; }
        public int Locked_dd { get; set; }
        public string Ghi_chu { get; set; }
        public Nullable<bool> Thieu_bai_thuc_hanh { get; set; }
    }
}
