//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("MARK_TotNghiep_DangKy")]
    public partial class MARK_TotNghiep_DangKy
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_SV { get; set; }
		
		[Display(Name = "Sinh viên - duyệt")]
        public bool SinhVien_Duyet { get; set; }
		
		[Display(Name = "Cố vấn - duyệt")]
        public bool CoVan_Duyet { get; set; }
    }
}
