//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("MARK_ToChucThiLapTuiThi_TC")]
    public partial class MARK_ToChucThiLapTuiThi_TC
    {
		[Key]
        public int ID { get; set; }
		
		[Display(Name = "ID thi")]
        public int ID_thi { get; set; }
		
		[Display(Name = "Túi số")]
        public int Tui_so { get; set; }
		
		[Display(Name = "STT")]
        public int STT { get; set; }
		
		[Display(Name = "Số báo danh")]
        public string So_bao_danh { get; set; }
		
		[Display(Name = "Số phách")]
        public int So_phach { get; set; }
		
		[Display(Name = "Điểm thi")]
        public Nullable<float> Diem_thi { get; set; }
		
		[Display(Name = "Ghi chú")]
        public string Ghi_chu { get; set; }
    }
}
