//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_DiemKyHieu
    {
        public string Ky_hieu { get; set; }
        public string Ten_ky_hieu { get; set; }
        public bool Hoc_lai { get; set; }
        public bool Co_ly_do { get; set; }
        public Nullable<bool> Khong_tinh_diem_thanh_phan { get; set; }
    }
}
