//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_NhomNguoiDung
    {
        public MOD_NhomNguoiDung()
        {
            this.MOD_NguoiDung = new HashSet<MOD_NguoiDung>();
        }
    
        public int ID_nhom_nd { get; set; }
        public string Ten_nhom { get; set; }
        public string Mo_ta { get; set; }
    
        public virtual ICollection<MOD_NguoiDung> MOD_NguoiDung { get; set; }
    }
}
