//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_HocKy
    {
        public MOD_HocKy()
        {
            this.MOD_LopTinChi_TC = new HashSet<MOD_LopTinChi_TC>();
        }
    
        public int ID_moodle { get; set; }
        public int Ky_dang_ky { get; set; }
    
        public virtual ICollection<MOD_LopTinChi_TC> MOD_LopTinChi_TC { get; set; }
    }
}
