//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_LopTinChi_TC
    {
        public MOD_LopTinChi_TC()
        {
            this.MOD_DanhSachLopTinChi = new HashSet<MOD_DanhSachLopTinChi>();
            this.MOD_NguoiDung_VaiTro_LopTinChi = new HashSet<MOD_NguoiDung_VaiTro_LopTinChi>();
            this.MOD_NhomHocVien = new HashSet<MOD_NhomHocVien>();
            this.MOD_ToNhom = new HashSet<MOD_ToNhom>();
        }
    
        public int ID_moodle { get; set; }
        public int ID_lop_tc { get; set; }
        public int ID_danhmuc { get; set; }
    
        public virtual ICollection<MOD_DanhSachLopTinChi> MOD_DanhSachLopTinChi { get; set; }
        public virtual MOD_HocKy MOD_HocKy { get; set; }
        public virtual ICollection<MOD_NguoiDung_VaiTro_LopTinChi> MOD_NguoiDung_VaiTro_LopTinChi { get; set; }
        public virtual ICollection<MOD_NhomHocVien> MOD_NhomHocVien { get; set; }
        public virtual ICollection<MOD_ToNhom> MOD_ToNhom { get; set; }
    }
}
