//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_ChuongTrinhDaoTaoKienThuc")]
    public partial class PLAN_ChuongTrinhDaoTaoKienThuc
    {
        [Key]
        public int ID_kien_thuc { get; set; }
		
		[Display(Name = "Tên kiến thức")]
        public string Ten_kien_thuc { get; set; }
    }
}
