//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_KeHoachKhac_TC
    {
        public int ID { get; set; }
        public Nullable<int> Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int ID_he { get; set; }
        public int ID_khoa { get; set; }
        public int Khoa_hoc { get; set; }
        public int ID_nganh { get; set; }
        public int ID_chuyen_nganh { get; set; }
        public System.DateTime Tu_ngay { get; set; }
        public System.DateTime Den_ngay { get; set; }
        public string Ky_hieu { get; set; }
        public bool Hien_thi { get; set; }
    }
}
