//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_DuBaoLopTinChiTh_TC
    {
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int ID_mon { get; set; }
        public int So_tin_chi { get; set; }
        public int So_sv { get; set; }
        public Nullable<int> So_lop { get; set; }
        public string Ky_hieu_lop { get; set; }
        public Nullable<int> So_sv_min { get; set; }
        public Nullable<int> So_sv_max { get; set; }
    }
}
