//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_ChucDanh")]
    public partial class PLAN_ChucDanh
    {
        [Key]
        public int ID_chuc_danh { get; set; }
		
		[Display(Name = "Mã chức danh")]
        public string Ma_chuc_danh { get; set; }
		
		[Display(Name = "Chức danh")]
        public string Chuc_danh { get; set; }
    }
}
