//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_LoaiLop_TC")]
    public partial class PLAN_LoaiLop_TC
    {
		[Key]
        public int Loai_lop { get; set; }
		
		[Display(Name = "Tên loại lớp")]
        public string Ten_loai_lop { get; set; }
    }
}
