//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_COSODAOTAO")]
    public partial class PLAN_COSODAOTAO
    {
        [Key]
        public int ID_co_so { get; set; }
		
		[Display(Name = "Mã cơ sở")]
        public string Ma_co_so { get; set; }
		
		[Display(Name = "Tên cơ sở")]
        public string Ten_co_so { get; set; }
    }
}
