//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_QUYDINH_DANGKY
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Tu_ngay { get; set; }
        public Nullable<System.DateTime> Den_ngay { get; set; }
        public Nullable<int> Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public Nullable<bool> Chon_dang_ky { get; set; }
        public Nullable<int> ID_he { get; set; }
        public Nullable<int> ID_Chuyen_nganh { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
