//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ChuongTrinhDaoTaoRangBuoc
    {
        [Key]
        public int ID_rb { get; set; }
        public Nullable<int> ID_dt { get; set; }
        public int ID_mon { get; set; }
        public int ID_mon_rb { get; set; }
        public int Loai_rang_buoc { get; set; }
    }
}
