//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ChuongTrinhDaoTaoChiTiet
    {
        [Key]
        public int ID_dt_mon { get; set; }
        public int ID_dt { get; set; }
        public int ID_mon { get; set; }
        public Nullable<int> Ky_thu { get; set; }
        public Nullable<float> So_hoc_trinh { get; set; }
        public Nullable<int> Ly_thuyet { get; set; }
        public Nullable<int> Thuc_hanh { get; set; }
        public Nullable<int> Bai_tap { get; set; }
        public Nullable<int> Bai_tap_lon { get; set; }
        public Nullable<int> Thuc_tap { get; set; }
        public Nullable<bool> Tu_chon { get; set; }
        public Nullable<int> STT_mon { get; set; }
        public Nullable<float> He_so { get; set; }
        public Nullable<int> Kien_thuc { get; set; }
        public Nullable<bool> Khong_tinh_TBCHT { get; set; }
        public Nullable<int> Nhom_tu_chon { get; set; }
        public Nullable<bool> Mon_tot_nghiep { get; set; }
        public Nullable<int> So_hoc_trinh_tien_quyet { get; set; }
        public Nullable<int> Tu_hoc { get; set; }
        public string Ma_khoa_phu_trach { get; set; }
        public int Mon_Main { get; set; }
        public int Nhom_mon_sub { get; set; }
    }
}
