//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_PhongHoc
    {
        [Key]
        public int ID_phong { get; set; }
        public Nullable<int> ID_co_so { get; set; }
        public Nullable<int> ID_nha { get; set; }
        public Nullable<int> ID_tang { get; set; }
        public string So_phong { get; set; }
        public string Loai_phong { get; set; }
        public Nullable<int> So_ban { get; set; }
        public Nullable<int> So_sv_mot_ban { get; set; }
        public Nullable<int> Suc_chua { get; set; }
        public Nullable<int> Suc_chua_thi { get; set; }
        public Nullable<bool> Am_thanh { get; set; }
        public Nullable<bool> May_tinh { get; set; }
        public Nullable<bool> Tivi { get; set; }
        public Nullable<bool> May_chieu { get; set; }
        public Nullable<int> So_sv { get; set; }
        public Nullable<int> ID_loai_phong { get; set; }
        public string Thiet_bi { get; set; }
        public int Khong_ToChucThi { get; set; }
    }
}
