//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_BôMnGiangVien")]
    public partial class PLAN_BoMonGiangVien
    {
        [Key]
        public int ID_bm { get; set; }
		
		[Display(Name = "ID_cb")]
        public int ID_cb { get; set; }
    }
}
