//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_PhamViDangKy_TC
    {
        [Key]
        public int ID_mon_tc { get; set; }
        public int ID_he { get; set; }
        public int ID_khoa { get; set; }
        public int Khoa_hoc { get; set; }
        public int ID_nganh { get; set; }
        public int ID_chuyen_nganh { get; set; }
    
        public virtual PLAN_MonTinChi_TC PLAN_MonTinChi_TC { get; set; }
    }
}
