//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_KeHoachThi_TC")]
    public partial class PLAN_KeHoachThi_TC
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_kh_thi { get; set; }
		
		[Display(Name = "ID_kh tuần")]
        public Nullable<int> ID_kh_tuan { get; set; }
		
		[Display(Name = "ID Môn")]
		[ForeignKey("MARK_MonHoc")]
        public Nullable<int> ID_mon { get; set; }
		
		[Display(Name = "ID Lớp")]
		[ForeignKey("STU_Lop")]
        public Nullable<int> ID_lop { get; set; }
		
		[Display(Name = "Ngày thi")]
        public Nullable<System.DateTime> Ngay_thi { get; set; }
		
		[Display(Name = "Ca thi")]
        public Nullable<int> Ca_thi { get; set; }
		
		[Display(Name = "Nhóm tiết")]
        public Nullable<int> Nhom_tiet { get; set; }
		
		[Display(Name = "Mô tả")]
        public string Mo_ta { get; set; }
		
		public virtual STU_Lop STU_Lop { get; set; }
		
		public virtual MARK_MonHoc MARK_MonHoc { get; set; }
    }
}
