//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_SuKienKhacPhongTinChi_TC
    {
        public long ID { get; set; }
        public Nullable<int> ID_phong { get; set; }
        public Nullable<int> Thu { get; set; }
        public Nullable<int> Tiet { get; set; }
        public Nullable<int> So_tiet { get; set; }
        public string Mo_ta { get; set; }
    }
}
