//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ChuongTrinhDaoTaoNhomTuChon
    {
        [Key]
        public int ID_dt { get; set; }
        public int Nhom_tu_chon { get; set; }
        public int So_mon_tu_chon { get; set; }
        public int So_mon_dang_ky { get; set; }
    }
}
