//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_MONDANGKY_HOCSOM
    {
        public int ID { get; set; }
        public Nullable<int> ID_sv { get; set; }
        public Nullable<int> ID_dt { get; set; }
        public Nullable<int> Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public Nullable<int> Tinh_chat { get; set; }
        public Nullable<int> ID_mon { get; set; }
        public Nullable<bool> Duyet { get; set; }
    }
}
