//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_DoiTuongHocBongGiayto")]
    public partial class STU_DoiTuongHocBongGiayto
    {
		[Display(Name = "Mã dt_hb")]
        public string Ma_dt_hb { get; set; }
		
		[Display(Name = "ID Giấy tờ")]
        public int ID_giay_to { get; set; }
    }
}
