//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_Doan")]
    public partial class STU_Doan
    {
		[Key]
        public int Doan { get; set; }
		
		[Display(Name = "Tên")]
        public string Ten { get; set; }
    }
}
