//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_QuyHocBong
    {
        [Key]
        public int ID_hb { get; set; }
        public int ID_quy { get; set; }
        public int ID_he { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int Tu_khoa { get; set; }
        public int Den_khoa { get; set; }
        public Nullable<decimal> Sotien_ngansach { get; set; }
        public Nullable<decimal> Sotien_khac { get; set; }
        public string Ghi_chu { get; set; }
    }
}
