//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_NoiNgoaiTru
    {
        [Key]
        public int ID_sv { get; set; }
        public System.DateTime Tu_ngay { get; set; }
        public Nullable<System.DateTime> Den_ngay { get; set; }
        public Nullable<int> ID_phong_ktx { get; set; }
        public string Dia_chi { get; set; }
        public string Dien_thoai { get; set; }
        public string Ten_chu_ho { get; set; }
        public string Ghi_chu { get; set; }
        public bool Trang_thai { get; set; }
        public Nullable<int> ID_phuong { get; set; }
    }
}
