//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_XepLoaiHocBong")]
    public partial class STU_XepLoaiHocBong
    {
        [Key]
        public int ID_xep_loai_hb { get; set; }
		
		[Display(Name = "Tên xếp loại")]
        public string Ten_xep_loai { get; set; }
		
		[Display(Name = "Từ điểm học tập")]
        public float Tu_diem_ht { get; set; }
		
		[Display(Name = "Từ điểm rèn luyện")]
        public float Tu_diem_rl { get; set; }
    }
}
