//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_KhuVuc")]
    public partial class STU_KhuVuc
    {
        [Key]
        public int ID_kv { get; set; }
		
		[Display(Name = "Mã khu vực")]
        public string Ma_kv { get; set; }
		
		[Display(Name = "Tên khu vực")]
        public string Ten_kv { get; set; }
    }
}
