//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_TruongTHPT
    {
        [Key]
        public string ID_THPT { get; set; }
        public string MATRUONG { get; set; }
        public string TENTRUONG { get; set; }
        public string DIACHI { get; set; }
        public string KHUVUC { get; set; }
    }
}
