//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_HeChuyenNganh")]
    public partial class STU_HeChuyenNganh
    {
        [Key]
        public int ID_he { get; set; }
		
		[Display(Name = "ID chuyên ngành")]
        public int ID_chuyen_nganh { get; set; }
    }
}
