//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_DanhHieu")]
    public partial class STU_DanhHieu
    {
        [Key]
        public int ID_danh_hieu { get; set; }
		
		[Display(Name = "Danh hiệu")]
        public string Danh_hieu { get; set; }
		
		[Display(Name = "Từ điểm")]
        public Nullable<int> Tu_diem { get; set; }
		
		[Display(Name = "Đến điểm")]
        public Nullable<int> Den_diem { get; set; }
    }
}
