//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_DinhMuc")]
    public partial class STU_DinhMuc
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_dm { get; set; }
		
		[Display(Name = "ID Chức danh")]
		[ForeignKey("STU_ChucDanh")]
        public int ID_chuc_danh { get; set; }
		
		[Display(Name = "ID Nhiệm vụ")]
        public int ID_nhiem_vu { get; set; }
		
		[Display(Name = "Số tiết")]
        public int So_tiet { get; set; }
		
		public virtual STU_ChucDanh STU_ChucDanh { get; set; }
    }
}
