//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_NhomDoiTuong
    {
        [Key]
        public int ID_nhom_dt { get; set; }
        public string Ma_nhom { get; set; }
        public string Ten_nhom { get; set; }
        public string Ten_nhom_en { get; set; }
    }
}
