//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_ThanhPhanXuatThan")]
    public partial class STU_ThanhPhanXuatThan
    {
        [Key]
        public int ID_thanh_phan_xuat_than { get; set; }
		
		[Display(Name = "Tên thành phần")]
        public string Ten_thanh_phan { get; set; }
    }
}
