//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_HoSoSinhVienSub
    {
        [Key]
        public int ID_sv { get; set; }
        public string Dia_chi_day_du { get; set; }
        public string So_dien_thoai { get; set; }
        public string Di_dong { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> ID_co_quan_lam_viec { get; set; }
        public Nullable<int> ID_tinh_chat_cong_viec { get; set; }
        public string Muc_thu_nhap_thang { get; set; }
        public Nullable<int> ID_noi_lam_viec { get; set; }
    }
}
