//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_XepLoaiHocBong
    {
        [Key]
        public int ID_xep_loai_hb { get; set; }
        public string Ten_xep_loai { get; set; }
        public float Tu_diem_ht { get; set; }
        public float Tu_diem_rl { get; set; }
    }
}
