//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_XeploaiRenLuyen
    {
        [Key]
        public int ID_xep_loai { get; set; }
        public string Xep_loai { get; set; }
        public Nullable<int> Tu_diem { get; set; }
        public Nullable<int> Den_diem { get; set; }
        public Nullable<float> He_so { get; set; }
    }
}
