//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_Lop
    {
        [Key]
        public int ID_lop { get; set; }
        public string Ten_lop { get; set; }
        public int ID_he { get; set; }
        public int ID_khoa { get; set; }
        public int ID_chuyen_nganh { get; set; }
        public int Khoa_hoc { get; set; }
        public string Nien_khoa { get; set; }
        public int ID_dt { get; set; }
        public Nullable<int> So_sv { get; set; }
        public bool Ra_truong { get; set; }
        public int Ca_hoc { get; set; }
        public int ID_phong { get; set; }
        public string Ho_ten_gv { get; set; }
        public string Dien_thoai { get; set; }
        public string Email { get; set; }
        public Nullable<int> Tinh_chat { get; set; }
        public Nullable<int> Lop_chuyen_nganh { get; set; }
        public Nullable<int> Lop_hanh_chinh { get; set; }
    }
}
