//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_GiaoVien
    {
        public int ID_cb { get; set; }
        public string Ma_cb { get; set; }
        public string Ten { get; set; }
        public string Ho_ten { get; set; }
        public Nullable<int> ID_gioi_tinh { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
        public int ID_khoa { get; set; }
        public int ID_hoc_ham { get; set; }
        public int ID_hoc_vi { get; set; }
        public int ID_chuc_danh { get; set; }
        public int ID_chuc_vu { get; set; }
    }
}
