//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    [Table("ACC_CHUYENKHOAN")]
    public partial class ACC_CHUYENKHOAN
    {
        public System.DateTime Ngay_giao_dich { get; set; }
        public string So_tai_khoan { get; set; }
        public string IDSV { get; set; }
        public Nullable<int> So_tien { get; set; }
        public Nullable<int> ID_bien_lai { get; set; }
    }
}
