//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    [Table("ACC_MucThuKhacSinhVien")]
    public partial class ACC_MucThuKhacSinhVien
    {
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int ID_sv { get; set; }
        public int ID_thu_chi { get; set; }
        public int So_tien { get; set; }
        public string Ngoai_te { get; set; }
        public string Ghi_chu { get; set; }
    }
}
