//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    [Table("ACC_ThiLai")]
    public partial class ACC_ThiLai
    {
        public int ID_thi_lai { get; set; }
        public Nullable<int> Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public Nullable<int> ID_he { get; set; }
        public Nullable<int> Ly_thuyet { get; set; }
        public Nullable<int> Thuc_hanh { get; set; }
    }
}
