//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_HocHam")]
    public partial class PLAN_HocHam
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_hoc_ham { get; set; }
		
		[Display(Name = "Mã học hàm")]
        public string Ma_hoc_ham { get; set; }
		
		[Display(Name = "Học hàm")]
        public string Hoc_ham { get; set; }
    }
}
