//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Final_TSEntities : DbContext
    {
        public Final_TSEntities()
            : base("name=Final_TSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ACC_BienLaiChi_Load_List(Nullable<int> hoc_ky, string nam_hoc, string dsID_lop, Nullable<int> iD_thu_chi, Nullable<int> thu_chi, Nullable<int> iD_sv)
        {
            var hoc_kyParameter = hoc_ky.HasValue ?
                new ObjectParameter("Hoc_ky", hoc_ky) :
                new ObjectParameter("Hoc_ky", typeof(int));
    
            var nam_hocParameter = nam_hoc != null ?
                new ObjectParameter("Nam_hoc", nam_hoc) :
                new ObjectParameter("Nam_hoc", typeof(string));
    
            var dsID_lopParameter = dsID_lop != null ?
                new ObjectParameter("dsID_lop", dsID_lop) :
                new ObjectParameter("dsID_lop", typeof(string));
    
            var iD_thu_chiParameter = iD_thu_chi.HasValue ?
                new ObjectParameter("ID_thu_chi", iD_thu_chi) :
                new ObjectParameter("ID_thu_chi", typeof(int));
    
            var thu_chiParameter = thu_chi.HasValue ?
                new ObjectParameter("Thu_chi", thu_chi) :
                new ObjectParameter("Thu_chi", typeof(int));
    
            var iD_svParameter = iD_sv.HasValue ?
                new ObjectParameter("ID_sv", iD_sv) :
                new ObjectParameter("ID_sv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_BienLaiChi_Load_List", hoc_kyParameter, nam_hocParameter, dsID_lopParameter, iD_thu_chiParameter, thu_chiParameter, iD_svParameter);
        }
    }
}
