//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_He
    {
        public int ID_he { get; set; }
        public string Ma_he { get; set; }
        public string Ten_he { get; set; }
        public int Quy_che { get; set; }
        public string Ten_he_en { get; set; }
        public string Ten_bac_hoc { get; set; }
        public string Loai_dao_tao { get; set; }
        public string Loai_dao_tao_en { get; set; }
    }
}
