//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    [Table("ACC_LoaiMienGiamNienKhoa")]
    public partial class ACC_LoaiMienGiamNienKhoa
    {
        public int ID_he { get; set; }
        public int Khoa_hoc { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int Loai_mien_giam { get; set; }
        public Nullable<int> So_tien_mien_giam_tren_mot_hoc_ky { get; set; }
    }
}
