//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
	using System;
	using System.Collections.Generic;

	[Table("ACC_BienLaiThuChiTiet_ThiLai")]
	public partial class ACC_BienLaiThuChiTiet_ThiLai
	{
		[Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
		public int ID_bien_lai_sub { get; set; }

		[ForeignKey("ACC_BienLaiThu_ThiLai")]
		public int ID_bien_lai { get; set; }

		[ForeignKey("ACC_LoaiThuChi")]
		public int ID_thu_chi { get; set; }

		public int ID_mon { get; set; }

		public int So_tien { get; set; }

		public virtual ACC_BienLaiThu_ThiLai ACC_BienLaiThu_ThiLai { get; set; }
		public virtual ACC_LoaiThuChi ACC_LoaiThuChi { get; set; }
	}
}
