//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_QUYDINH_DANGKY")]
    public partial class PLAN_QUYDINH_DANGKY
    {
		[Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
		
		[Display(Name = "Từ ngày")]
        public Nullable<System.DateTime> Tu_ngay { get; set; }
		
		[Display(Name = "Đến ngày")]
        public Nullable<System.DateTime> Den_ngay { get; set; }
		
		[Display(Name = "Học kỳ")]
        public Nullable<int> Hoc_ky { get; set; }
		
		[Display(Name = "Năm học")]
        public string Nam_hoc { get; set; }
		
		[Display(Name = "Chọn đăng ký")]
        public Nullable<bool> Chon_dang_ky { get; set; }
		
		[Display(Name = "ID Hệ")]
		[ForeignKey("STU_He")]
        public Nullable<int> ID_he { get; set; }
		
		[Display(Name = "ID Chuyên ngành")]
		[ForeignKey("STU_ChuyenNganh")]
        public Nullable<int> ID_Chuyen_nganh { get; set; }

        [ForeignKey("PLAN_HocKyDangKy_TC")]
        public int Ky_dang_ky { get; set; }

        [Display(Name="Khóa học")]
        public int Khoa_hoc { get; set; }
		
		[Display(Name = "Type")]
        public Nullable<int> Type { get; set; }
		
		public virtual STU_He STU_He { get; set; }
		
		public virtual STU_ChuyenNganh STU_ChuyenNganh { get; set; }

        [Display(Name="Kỳ đăng ký")]
        public virtual PLAN_HocKyDangKy_TC PLAN_HocKyDangKy_TC { get; set; }
    }
}
