//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_ChuyenNganh")]
    public partial class STU_ChuyenNganh
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_chuyen_nganh { get; set; }
		
		[Display(Name = "Mã chuyên ngành")]
        public string Ma_chuyen_nganh { get; set; }
		
		[Display(Name = "Chuyên ngành")]
        public string Chuyen_nganh { get; set; }
		
		[Display(Name = "ID ngành")]
		[ForeignKey("STU_Nganh")]
        public int ID_nganh { get; set; }
		
		[Display(Name = "Chuyên ngành EN")]
        public string Chuyen_nganh_En { get; set; }
		
		[Display(Name = "Kỹ thuật")]
        [ForeignKey("STU_Bit")]
        public int Ky_thuat { get; set; }
    
        public virtual STU_Nganh STU_Nganh { get; set; }

        public virtual STU_Bit STU_Bit { get; set; }
    }
}
