//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_TruongTHPT")]
    public partial class STU_TruongTHPT
    {
        [Key]
        public string ID_THPT { get; set; }
		
		[Display(Name = "Mã trường")]
        public string MATRUONG { get; set; }
		
		[Display(Name = "Tên trường")]
        public string TENTRUONG { get; set; }
		
		[Display(Name = "Địa chỉ")]
        public string DIACHI { get; set; }
		
		[Display(Name = "Khu vực")]
        public string KHUVUC { get; set; }
    }
}
