//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table ("STU_DanhSachLopTinChi")]
    public partial class STU_DanhSachLopTinChi
    {
		[Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
		
		[Display(Name = "ID Lớp TC")]
		[ForeignKey("PLAN_LopTinChi_TC")]
        public int ID_lop_tc { get; set; }
		
		[Display(Name = "ID SV")]
		[ForeignKey("STU_HoSoSinhVien")]
        public int ID_sv { get; set; }
		
		[Display(Name = "Học lại")]
        public int Hoc_lai { get; set; }
		
		[Display(Name = "Duyệt")]
        public int Duyet { get; set; }
		
		[Display(Name = "Hủy đăng ký")]
        public bool Huy_dang_ky { get; set; }
		
		[Display(Name = "Lý do")]
        public string Ly_do { get; set; }
		
		[Display(Name = "Rút bớt học phần")]
        public Nullable<bool> Rut_bot_hoc_phan { get; set; }
		
		[Display(Name = "Chuyên ngành 2")]
        public bool Chuyen_nganh2 { get; set; }
		
		[Display(Name = "CLC")]
        public Nullable<bool> CLC { get; set; }

        [ForeignKey("STU_DanhSach")]
        public int? ID_danh_sach { get; set; }
		
		public virtual PLAN_LopTinChi_TC PLAN_LopTinChi_TC { get; set; }
		
		public virtual STU_HoSoSinhVien STU_HoSoSinhVien { get; set; }

       public virtual STU_DanhSach STU_DanhSach { get; set; }
    }
}
