//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_BienLaiThuHocLai
    {
        public int ID_bien_lai { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int Dot_thu { get; set; }
        public int Lan_thu { get; set; }
        public int ID_sv { get; set; }
        public bool Thu_chi { get; set; }
        public int So_phieu { get; set; }
        public System.DateTime Ngay_thu { get; set; }
        public string Noi_dung { get; set; }
        public int So_tien { get; set; }
        public string So_tien_chu { get; set; }
        public string Ngoai_te { get; set; }
        public bool Huy_phieu { get; set; }
        public string Ghi_chu { get; set; }
        public string Nguoi_thu { get; set; }
        public bool Printed { get; set; }
        public Nullable<bool> Gian_thu { get; set; }
        public string so_phieu_header { get; set; }
    }
}
