//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark_DanhSachThiTotNghiep
    {
        [Key]
        public int ID_sv { get; set; }
        public Nullable<float> TBCHT { get; set; }
        public Nullable<int> ID_xep_loai { get; set; }
        public float So_tin_chi { get; set; }
        public bool Sinh_vien_duyet { get; set; }
        public string Y_kien_co_van { get; set; }
        public bool Co_van_duyet { get; set; }
    }
}
