//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_ToChucThiPhong_TC
    {
        [Key]
        public int ID_phong_thi { get; set; }
        public int ID_lop_tc { get; set; }
        public int ID_phong { get; set; }
        public string Ten_phong { get; set; }
        public int So_sv { get; set; }
        public Nullable<int> Dot_thi { get; set; }
        public Nullable<System.DateTime> Ngay_thi { get; set; }
        public Nullable<int> Ca_thi { get; set; }
        public Nullable<int> Nhom_tiet { get; set; }
        public string Gio_thi { get; set; }
    }
}
