//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("Mark_DanhSachLuanVan")]
    public partial class Mark_DanhSachLuanVan
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_sv { get; set; }
		
		[Display(Name = "TBCHT")]
        public Nullable<float> TBCHT { get; set; }
		
		[Display(Name = "Số tín chỉ")]
        public float So_tin_chi { get; set; }
		
		[Display(Name = ""ID Xếp loại)]
		[ForeignKey("MARK_XepLoaiHocTap_TC")]
        public Nullable<int> ID_xep_loai { get; set; }
		
		[Display(Name = "Sinh viên duyệt")]
        public int Sinh_vien_duyet { get; set; }
		
		[Display(Name = "Ý kiến Cố vấn")]
        public string Y_kien_co_van { get; set; }
		
		[Display(Name = "Cố vấn duyệt")]
        public bool Co_van_duyet { get; set; }
		
		public virtual MARL_XepLoaiHocTap_TC MARK_XepLoaiHocTap_TC { get; set; }
    }
}
