//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_ToChucThiLapTuiThi_TC
    {
        public int ID { get; set; }
        public int ID_thi { get; set; }
        public int Tui_so { get; set; }
        public int STT { get; set; }
        public string So_bao_danh { get; set; }
        public int So_phach { get; set; }
        public Nullable<float> Diem_thi { get; set; }
        public string Ghi_chu { get; set; }
    }
}
