//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark_DanhSachChuaTotNghiep
    {
        [Key]
        public int ID_sv { get; set; }
        public Nullable<float> TBCHT { get; set; }
        public Nullable<int> ID_xep_loai { get; set; }
        public string Ly_do { get; set; }
        public string Nam_hoc { get; set; }
        public Nullable<int> Id_dt { get; set; }
        public string Phan_tram_thi_lai { get; set; }
    }
}
