//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_DiemThi
    {
        [Key]
        public int ID_diem_thi { get; set; }
        public int ID_diem { get; set; }
        public int Lan_hoc { get; set; }
        public int Lan_thi { get; set; }
        public Nullable<float> Diem_thi { get; set; }
        public Nullable<float> TBCHP { get; set; }
        public Nullable<int> Hash_code { get; set; }
        public Nullable<int> Locked { get; set; }
        public string Ghi_chu { get; set; }
    }
}
