//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_ToChucThiDangKyCaiThienDiem_TC
    {
        public int ID { get; set; }
        public int Id_sv { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int Id_mon { get; set; }
        public int ID_dt { get; set; }
        public int Duyet { get; set; }
        public string Ghi_chu { get; set; }
    }
}
