//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_DanhSachTotNghiep
    {
        [Key]
        public int ID_sv { get; set; }
        public int Lan_thu { get; set; }
        public int So_bang { get; set; }
        public float TBCHT10 { get; set; }
        public float TBCHT { get; set; }
        public int ID_xep_loai { get; set; }
        public string Nam_hoc { get; set; }
        public string So_bang_txt { get; set; }
        public string So_serial_txt { get; set; }
        public Nullable<int> Id_dt { get; set; }
        public float phantram_thilai { get; set; }
        public string So_QD { get; set; }
        public Nullable<System.DateTime> Ngay_QD { get; set; }
    }
}
