//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_Diem_TC
    {
        public MARK_Diem_TC()
        {
            this.MARK_DiemThanhPhan_TC = new HashSet<MARK_DiemThanhPhan_TC>();
            this.MARK_DiemThi_TC = new HashSet<MARK_DiemThi_TC>();
        }
    
        public int ID_diem { get; set; }
        public string ID_dv { get; set; }
        public int ID_sv { get; set; }
        public int ID_mon { get; set; }
        public int ID_dt { get; set; }
        public Nullable<float> TBCMH_Lan1 { get; set; }
        public Nullable<float> TBCMH_Max { get; set; }
        public string DIEM_THIs { get; set; }
        public string DIEM_CHUs { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public Nullable<bool> Duyet { get; set; }
        public Nullable<bool> Tinh_tich_luy { get; set; }
    
        public virtual MARK_MonHoc MARK_MonHoc { get; set; }
        public virtual PLAN_ChuongTrinhDaoTao PLAN_ChuongTrinhDaoTao { get; set; }
        public virtual STU_HoSoSinhVien STU_HoSoSinhVien { get; set; }
        public virtual ICollection<MARK_DiemThanhPhan_TC> MARK_DiemThanhPhan_TC { get; set; }
        public virtual ICollection<MARK_DiemThi_TC> MARK_DiemThi_TC { get; set; }
    }
}
