//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_DiemThi_TC
    {
        [Key]
        public int ID_diem_thi { get; set; }
        public int ID_diem { get; set; }
        public int Lan_thi { get; set; }
        public int Hoc_ky_thi { get; set; }
        public string Nam_hoc_thi { get; set; }
        public float Diem_thi { get; set; }
        public string Diem_chu { get; set; }
        public float TBCMH { get; set; }
        public int Hash_code { get; set; }
        public int Locked { get; set; }
        public string Ghi_chu { get; set; }
    
        public virtual MARK_Diem_TC MARK_Diem_TC { get; set; }
    }
}
