//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("Mark_DanhSachThucTap")]
    public partial class Mark_DanhSachThuctap
    {
        [Key]
        public int ID_sv { get; set; }
		
		[Display(Name = "Nơi thực tập")]
        public string Noi_thuc_tap { get; set; }
    }
}
