//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_XetLenLopTongHop_TC
    {
        public string Nam_hoc { get; set; }
        public int ID_lop { get; set; }
        public Nullable<int> Hoc_tiep { get; set; }
        public Nullable<int> Thoi_hoc1 { get; set; }
        public Nullable<int> Thoi_hoc2 { get; set; }
        public Nullable<int> Thoi_hoc3 { get; set; }
        public Nullable<int> Thoi_hoc4 { get; set; }
        public Nullable<int> Thoi_hoc5 { get; set; }
        public Nullable<int> Ngung_hoc1 { get; set; }
        public Nullable<int> Ngung_hoc2 { get; set; }
        public Nullable<int> Ngung_hoc3 { get; set; }
        public string Ghi_chu { get; set; }
    }
}
