//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("MARK_ToChucThiPhong")]
    public partial class MARK_ToChucThiPhong
    {
        [Key]
        public int ID_phong_thi { get; set; }
		
		[Display(Name = "Tên phòng")]
        public string Ten_phong { get; set; }
		
		[Display(Name = "Số sv")]
        public int So_sv { get; set; }
    }
}
