//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_DichVu
    {
        public MOD_DichVu()
        {
            this.MOD_Quyen = new HashSet<MOD_Quyen>();
        }
    
        public int ID_dv { get; set; }
        public string Ten_dv { get; set; }
        public string Ten_rut_gon { get; set; }
        public Nullable<bool> Root { get; set; }
    
        public virtual ICollection<MOD_Quyen> MOD_Quyen { get; set; }
    }
}
