//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_Quyen
    {
        public MOD_Quyen()
        {
            this.MOD_DichVu = new HashSet<MOD_DichVu>();
        }
    
        public int ID_quyen { get; set; }
        public string Ten_quyen { get; set; }
        public string Action_name { get; set; }
    
        public virtual ICollection<MOD_DichVu> MOD_DichVu { get; set; }
    }
}
