//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_QuyDinhSoTinChi_TC
    {
        [Key]
        public int ID_he { get; set; }
        public int ID_khoa { get; set; }
        public int Khoa_hoc { get; set; }
        public int Ky_dang_ky { get; set; }
        public Nullable<int> So_hoc_trinh_min_bt { get; set; }
        public Nullable<int> So_hoc_trinh_max_bt { get; set; }
        public Nullable<int> So_hoc_trinh_option_bt { get; set; }
        public Nullable<bool> Check_so_hoc_trinh_min_bt { get; set; }
        public Nullable<bool> Check_so_hoc_trinh_max_bt { get; set; }
        public Nullable<int> So_hoc_trinh_min_yeu { get; set; }
        public Nullable<int> So_hoc_trinh_max_yeu { get; set; }
        public Nullable<int> So_hoc_trinh_option_yeu { get; set; }
        public Nullable<bool> Check_so_hoc_trinh_min_yeu { get; set; }
        public Nullable<bool> Check_so_hoc_trinh_max_yeu { get; set; }
        public Nullable<System.DateTime> Tu_ngay1 { get; set; }
        public Nullable<System.DateTime> Den_ngay1 { get; set; }
        public Nullable<System.DateTime> Tu_ngay2 { get; set; }
        public Nullable<System.DateTime> Den_ngay2 { get; set; }
    }
}
