//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_LoaiRangBuoc")]
    public partial class PLAN_LoaiRangBuoc
    {
		[Key]
        public int Loai_rang_buoc { get; set; }
		
		[Display(Name = "Tên ràng buộc")]
        public string Ten_rang_buoc { get; set; }
    }
}
