//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_BoMon")]
    public partial class PLAN_BoMon
    {
        [Key]
        public int ID_bm { get; set; }
		
		[Display(Name = "Mã bộ môn")]
        public string Ma_bo_mon { get; set; }
		
		[Display(Name = "Bộ môn")]
        public string Bo_mon { get; set; }
		
		[Display(Name = "Số nhóm")]
        public Nullable<int> So_nhom { get; set; }
    }
}
