//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_DangKyThucTap_TC")]
    public partial class PLAN_DangKyThucTap_TC
    {
        [Key]
        public int ID_sv { get; set; }
		
		[Display(Name = "ID_kh_tt")]
        public int ID_kh_tt { get; set; }
    }
}
