//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_MonDangKy_TC
    {
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int ID_sv { get; set; }
        public int ID_mon { get; set; }
        public int So_hoc_trinh { get; set; }
        public int ID_dt { get; set; }
    
        public virtual MARK_MonHoc MARK_MonHoc { get; set; }
    }
}
