//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("PLAN_LopTinChiGanLopHanhChinh_TC")]
    public partial class PLAN_LopTinChiGanLopHanhChinh_TC
    {
		[Key]
        public int ID { get; set; }
		
		[Display(Name = "ID Lớp TC")]
        public int ID_lop_tc { get; set; }
		
		[Display(Name = "ID Lớp HC")]
        public int ID_lop_hc { get; set; }
    }
}
