//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_RangBuocNganhNhapHoc
    {
        [Key]
        public int ID_rb { get; set; }
        public int Nam_hoc { get; set; }
        public int Loai { get; set; }
        public Nullable<int> ID_Nganh { get; set; }
        public int ID_chuyen_nganh { get; set; }
    }
}
