//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_HoatDongXaHoi
    {
        [Key]
        public int ID_hd_xh { get; set; }
        public int ID_sv { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public System.DateTime Ngay_thang { get; set; }
        public string Noi_dung { get; set; }
        public string Ket_qua { get; set; }
        public Nullable<int> Diem_thuong { get; set; }
    }
}
