//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_KyLuatSinhVien
    {
        [Key]
        public int ID_ky_luat { get; set; }
        public int ID_sv { get; set; }
        public bool Xoa_ky_luat { get; set; }
        public Nullable<System.DateTime> Ngay_Xoa { get; set; }
        public string Lydo_Xoa { get; set; }
    }
}
