//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_LoaiGiayTo
    {
        [Key]
        public int ID_giay_to { get; set; }
        public string Ma_giay_to { get; set; }
        public string Ten_giay_to { get; set; }
        public int So_luong { get; set; }
        public bool An { get; set; }
    }
}
