//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_DanhSachLopTinChi
    {
        public int ID { get; set; }
        public int ID_lop_tc { get; set; }
        public int ID_sv { get; set; }
        public int Hoc_lai { get; set; }
        public int Duyet { get; set; }
        public bool Huy_dang_ky { get; set; }
        public string Ly_do { get; set; }
        public Nullable<bool> Rut_bot_hoc_phan { get; set; }
        public bool Chuyen_nganh2 { get; set; }
        public Nullable<bool> CLC { get; set; }
    }
}
