//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_XuLy")]
    public partial class STU_XuLy
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_xu_ly { get; set; }

        [Display(Name = "ID Cấp")]
        [ForeignKey ("STU_CapKhenThuongKyLuat")]
        public int ID_cap { get; set; }

        [Display(Name = "Số tháng")]
        public int So_thang { get; set; }

        [Display(Name = "Xử lý")]
        public string Xu_ly { get; set; }

        [Display(Name = "Điểm phạt")]
        public float Diem_phat { get; set; }

        [Display(Name = "Mức xử lý")]
        public int Muc_xu_ly { get; set; }

        public virtual STU_CapKhenThuongKyLuat STU_CapKhenThuongKyLuat { get; set; }
    }
}
