//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_LoaiHocBong
    {
        public string Ma_dt { get; set; }
        public int ID_he { get; set; }
        public int ID_xep_loai_hb { get; set; }
        public int HB_HT { get; set; }
    }
}
