//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_ChuyenNganh
    {
        [Key]
        public int ID_chuyen_nganh { get; set; }
        public string Ma_chuyen_nganh { get; set; }
        public string Chuyen_nganh { get; set; }
        public int ID_nganh { get; set; }
        public string Chuyen_nganh_En { get; set; }
        public bool Ky_thuat { get; set; }
    
        public virtual STU_Nganh STU_Nganh { get; set; }
    }
}
