//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_HoSoMacDinh
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string ID_tinh_ns { get; set; }
        public string ID_Tinh_tt { get; set; }
        public string ID_Huyen_tt { get; set; }
        public Nullable<int> ID_Dan_toc { get; set; }
        public string Ton_giao { get; set; }
        public string Ma_dt { get; set; }
        public Nullable<int> ID_nhom_dt { get; set; }
        public string Ma_kv { get; set; }
        public Nullable<bool> ID_gioi_tinh { get; set; }
        public string Khoi_thi { get; set; }
        public Nullable<bool> Doan { get; set; }
        public Nullable<bool> Dang { get; set; }
    }
}
