//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_ChungChiSinhVien")]
    public partial class STU_ChungChiSinhVien
    {
        [Key]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID_sv { get; set; }
		
		[Display(Name = "ID_đt")]
		[ForeignKey("STU_DoiTuong")]
        public int ID_dt { get; set; }
		
		[Display(Name = "ID Chứng chỉ")]
		[ForeignKey("MARK_LoaiChungChi")]
        public int ID_chung_chi { get; set; }
		
		[Display(Name = "Lần xét")]
        public int Lan_xet { get; set; }
		
		[Display(Name = "ID Xếp loại")]
		[ForeignKey("STU_XepLoaiRenLuyen")]
        public Nullable<int> ID_xep_loai { get; set; }
		
		[Display(Name = "TBCHT")]
        public Nullable<float> TBCHT { get; set; }
		
		public virtual STU_DoiTuong STU_DoiTuong { get; set; }
		
		public virtual MARK_LoaiChungChi MARK_LoaiChungChi { get; set; }
		
		public virtual STU_XepLoaiRenLuyen STU_XepLoaiRenLuyen { get; set; }
    }
}
