//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_ChungChiSinhVien
    {
        [Key]
        public int ID_sv { get; set; }
        public int ID_dt { get; set; }
        public int ID_chung_chi { get; set; }
        public int Lan_xet { get; set; }
        public Nullable<int> ID_xep_loai { get; set; }
        public Nullable<float> TBCHT { get; set; }
    }
}
