//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_Huyen")]
    public partial class STU_Huyen
    {
        [Key]
        public string ID_huyen { get; set; }
		
		[Display(Name = "ID Tỉnh")]
		[ForeignKey("STU_Tinh")]
        public string ID_tinh { get; set; }
		
		[Display(Name = "Tên huyện")]
        public string Ten_huyen { get; set; }
		
		[Display(Name = "Tên huyện EN")]
        public string Ten_huyen_en { get; set; }
		
		public virtual STU_Tinh STU_Tinh { get; set; }
    }
}
