//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_XetHocBong
    {
        [Key]
        public int ID_phan_bo { get; set; }
        public int Phuong_an { get; set; }
        public int Lan_xet { get; set; }
        public bool Chon_phuong_an { get; set; }
        public string Ma_dt_hb { get; set; }
        public string Ten_dt_hb { get; set; }
        public float Diem_chuan { get; set; }
        public int So_sv { get; set; }
        public int So_tien { get; set; }
    }
}
