//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_KyLuat
    {
        [Key]
        public int ID_ky_luat { get; set; }
        public string So_qd { get; set; }
        public Nullable<System.DateTime> Ngay_qd { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public int ID_hanh_vi { get; set; }
        public int ID_xu_ly { get; set; }
        public string Noi_dung { get; set; }
    }
}
