//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_Tinh")]
    public partial class STU_Tinh
    {
        [Key]
        public string ID_tinh { get; set; }
		
		[Display(Name = "Tên tỉnh")]
        public string Ten_tinh { get; set; }
		
		[Display(Name = "Tên tỉnh En")] 
        public string Ten_tinh_en { get; set; }
    }
}
