//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_QuyHocBongPhanBo
    {
        [Key]
        public int ID_phan_bo { get; set; }
        public string Ten_phan_bo { get; set; }
        public int ID_hb { get; set; }
        public int So_sv { get; set; }
        public long So_tien { get; set; }
        public bool Phan_dac_biet { get; set; }
    }
}
