//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_HeSoRenLuyen")]
    public partial class STU_HeSoRenLuyen
    {
        [Key]
        public int ID { get; set; }
		
		[Display(Name = "Năm thứ")]
        public int Nam_thu { get; set; }
		
		[Display(Name = "Hệ số")]
        public float He_so { get; set; }
    }
}
