//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_DoiTuong
    {
        [Key]
        public int ID_dt { get; set; }
        public string Ma_dt { get; set; }
        public string Ten_dt { get; set; }
        public int Phan_tram_mien_giam { get; set; }
        public Nullable<int> Nhom_ut { get; set; }
    }
}
