//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    [Table("STU_DoiTuongHocBong")]
    public partial class STU_DoiTuongHocBong
    {
        [Key]
        public int ID_dt_hb { get; set; }
		
		[Display(Name = "Mã dt_hb")]
        public string Ma_dt_hb { get; set; }
		
		[Display(Name = "Tên dt_hb")]
        public string Ten_dt_hb { get; set; }
		
		[Display(Name = "Số tiền trợ cấp")]
        public int Sotien_trocap { get; set; }
    }
}
