//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STU_DinhMuc
    {
        [Key]
        public int ID_dm { get; set; }
        public int ID_chuc_danh { get; set; }
        public int ID_nhiem_vu { get; set; }
        public int So_tiet { get; set; }
    }
}
